### PR TITLE
Adapt icon removal from core and bump core requirement to 2.319.3

### PR DESCRIPTION
**Pull request by NotMyFault**
Fixes [JENKINS-67176](https://issues.jenkins.io/browse/JENKINS-67176)

The change proposed adapts the icon removal from core and bumps the base line to a modern version of Jenkins.
JSR 305 has been replaced with findbugs annotations, because it's EOL and the bom offers findbugs as replacement.

cc @olamy if you mind taking a look :)

Closes https://github.com/jenkinsci/favorite-plugin/pull/68 as well

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira

### CODE REVIEW

**Comment by NotMyFault** [comment]
ci.jenkins.io does not accept Jenkinsfile modifications from foreign PRs on the PR itself, hence the build fails, because it builds with 2.222 instead of 2.319.3.
However, tests are working fine, according to GitHub actions and to my local testing.
Do you mind giving it a review nevertheless, @olamy :)

**Comment by boczh** [comment]
Hello, just wondering if there is any timeline on approximately when will this PR be merged and new plugin version released?

**Comment by NotMyFault** [comment]
> Hello, just wondering if there is any timeline on approximately when will this PR be merged and new plugin version released?

Anytime, once a maintainer reviews it. In the meantime, you can either build it yourself or use my build binaries: https://keybase.pub/notmyfault_og/jenkins/favorite-plugin/

**Comment by olamy** [comment]
release done.
sorry guys for delay I have missed the ping (and notifications were lost in a huge stack :( )

**Comment by NotMyFault** [comment]
No worries, thanks for taking care of it 👍🏻

**Pull request merged**
