### PR TITLE
Standard Jenkinsfile

### PR DESCRIPTION
**Pull request by jglick**
Simpler, and the current one fails to archive artifacts or test on Windows, among other things.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Weird, this is being built on ci.blueocean.io as well as ci.jenkins.io. Why @i386? The plugin is not a part of Blue Ocean.

**Comment by i386** [comment]
@jglick because we've adopted it and we want to monitor it in the same place we monitor other plugins we care about.

**Comment by oleg-nenashev** [comment]
@i386 @jglick Probably we could use an 'if' check with condition like https://github.com/jenkins-infra/pipeline-library/blob/master/vars/infra.groovy#L3-L5 to have different behaviors on ci.jenkins.io and ci.blueocean.io

**Comment by i386** [comment]
@oleg-nenashev @jglick I assume there is a shared library that exposes `buildPlugin`? We could just register that on blueocean.io and call it a day.

**Comment by oleg-nenashev** [comment]
@i386 you could, bu in such case you need to setup the environment required by the library. In particular, Maven/JDK tools and Windows build agents

**Comment by jglick** [comment]
Maintaining two similar yet subtly different CI servers for `jenkinsci/*-plugin` sounds like a bad plan to me. Confusing for contributors. At least `favorite` and `display-url-api` are independent of Blue Ocean and should be hosted on the general server.

**Comment by i386** [comment]
@jglick if thats what you want I won't argue with it.

**Comment by jglick** [comment]
Looks like this has in fact been removed from https://ci.blueocean.io/job/jenkinsci/ so it should be safe to merge this.

**Pull request merged**
