### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
@jenkinsci/reviewer Anyone help to review this pr?

**Comment by larrys** [comment]
@LinuxSuRen I no longer maintain this plugin. You will need to ping @i386 possibly.

**Comment by LinuxSuRen** [comment]
@larrys Thanks for your tip, @i386 Can you help to review this?

**Comment by i386** [comment]
Ive asked for help on the mailing list to review https://groups.google.com/forum/?nomobile=true#!topic/jenkinsci-dev/SsC6vQg4k-I

**Comment by LinuxSuRen** [comment]
Thank you, I can not visit google website. @i386

**Comment by daniel-beck** [comment]
@i386 FYI the author has contributed quite a few Chinese translations to core in the past: https://github.com/jenkinsci/jenkins/pulls?q=is%3Apr+author%3Alinuxsuren+is%3Aclosed

I usually check some HTML file translations in Google translate, and they all seemed reasonable. So if @LinuxSuRen is out to mess with us, they've already gotten into core 🤷‍♂️

**Comment by i386** [comment]
SGTM

**Comment by ijyun** [comment]
@i386 Hi James,I could help to translate into Chinese.I'm wondering is the requirement is to translate the README.md file? there is not much notice, thanks.

**Pull request merged**
