### PR TITLE
JENKINS-50603: Verify that the job was a favorite before adding it again

### PR DESCRIPTION
**Pull request by deepy**
This fixes JENKINS-50603.

Verify that the job was a favorite before doing anything with it.

### CODE REVIEW

**Comment by deepy** [comment]
@i386

**Comment by i386** [comment]
@deepy could we get a test case for this one, please?

**Comment by deepy** [comment]
@i386 tests added!

CI seems to be doing something weird, but the tests pass locally.

**Comment by i386** [comment]
@vivek mind giving this one a review? Could probably release it too

**Comment by deepy** [comment]
@i386 any chance of getting this merged and released :-)?

**Comment by michaelneale** [comment]
sorry about this @deepy - it slipped through the cracks. 

@vivek I have set you up with commit access, just need https://github.com/jenkins-infra/repository-permissions-updater/pull/701 to be merged so you can do a release as needed.

**Comment by michaelneale** [comment]
thanks for test too @deepy

**Pull request merged**
