### PR TITLE
[JENKINS-44797] Switch to adjuncts

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-44797](https://issues.jenkins-ci.org/browse/JENKINS-44797)

#12 was not effective. I do not know how to reproduce from scratch (I can see the error consistently but on servers I have no admin access to), but at least this is using a standard idiom.

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
hrm right... so JENKINS-39990 wasn't fixed. ping @i386

**Comment by jglick** [comment]
Deployed on a test server where the error was previously reproducible, and now it is not.

**Comment by i386** [comment]
🐝

**Comment by i386** [comment]
We lost i18n for the hovers :(

**Comment by i386** [comment]
Released as 2.3.1 and release notes updated.

**Pull request merged**
